version: 2.1
# Use a package of configuration called an orb.

jobs:
    deploy:
      docker:
      - image: circleci/openjdk:8u171
      working_directory: ~/ci

      steps:
        - checkout
        - run: |
            mkdir deploy
            echo "Repo: $CIRCLE_PROJECT_REPONAME, buildnum: $CIRCLE_BUILD_NUM" > deploy/circleci_$CIRCLE_BUILD_NUM.txt
            echo "branch $CIRCLE_BRANCH" > deploy/branch_$CIRCLE_BRANCH.txt
            apt-get install zip && zip - deploy.zip deploy
        - store_artifacts:
            path: ~/ci/deploy.


  # Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - deploy